['header','main','footer'].forEach(selector=>document.querySelectorAll(`body > ${selector}`).forEach((node,index)=>{if(index>0)node.remove()}));
const navStyles=document.createElement('link');navStyles.rel='stylesheet';navStyles.href='css/nav.css';document.head.append(navStyles);
if(!document.querySelector('.page-header')&&document.querySelector('.thanks'))document.body.insertAdjacentHTML('afterbegin','<header class="page-header"><a class="brand" href="index.html"><img src="assets/images/logo/logo.png" alt="Ruchi"><span>Ruchi<small>RESTAURANT</small></span></a><button class="nav-toggle" aria-label="Open menu" aria-expanded="false">☰</button><nav class="nav-links"></nav></header>');
document.querySelectorAll('.page-header').forEach(header=>{const nav=header.querySelector('nav');if(!nav)return;nav.className='nav-links';nav.innerHTML='<a href="about.html">Our story</a><a href="menu.html">Menu</a><a href="index.html#gallery">Gallery</a><a href="faq.html">FAQ</a><a href="history.html">Order history</a><a href="login.html">Sign in</a><a href="cart.html">Cart <b data-cart-count>0</b></a><a class="nav-book" href="booking.html">Book a table</a>';if(!header.querySelector('.nav-toggle')){const toggle=document.createElement('button');toggle.className='nav-toggle';toggle.type='button';toggle.setAttribute('aria-label','Open menu');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰';header.insertBefore(toggle,nav)}});
const dishes = [
  {id:1,name:'Chicken Biryani',category:'main',price:220,rating:'4.8',image:'assets/images/img/signature dish.png',description:'Aromatic basmati rice, tender chicken and house spices.'},
  {id:2,name:'Mutton Biryani',category:'main',price:280,rating:'4.9',image:'assets/images/img/special_dish.jpeg',description:'Slow-cooked mutton layered with saffron rice.'},
  {id:3,name:'Chicken Curry',category:'main',price:180,rating:'4.7',image:'assets/images/img/chef.jpeg',description:'Home-style chicken curry in a rich, spiced gravy.'},
  {id:4,name:'Paneer Butter Masala',category:'main',price:160,rating:'4.7',image:'assets/images/img/starters.jpeg',description:'Soft paneer in a velvety tomato-butter sauce.'},
  {id:5,name:'Masala Dosa',category:'south',price:80,rating:'4.8',image:'assets/images/img/south_indian_special.jpeg',description:'Golden crisp dosa with classic potato masala.'},
  {id:6,name:'Ghee Roast',category:'south',price:100,rating:'4.8',image:'assets/images/img/south_indian_special.jpeg',description:'Extra-crisp dosa finished with fragrant ghee.'},
  {id:7,name:'Idli Sambar',category:'south',price:50,rating:'4.6',image:'assets/images/img/exterior.jpeg',description:'Cloud-soft idlis with sambar and coconut chutney.'},
  {id:8,name:'Pongal',category:'south',price:70,rating:'4.6',image:'assets/images/img/starters.jpeg',description:'Comforting rice and lentils tempered with ghee.'},
  {id:9,name:'Chicken 65',category:'starter',price:160,rating:'4.8',image:'assets/images/img/deserts2.jpeg',description:'Crispy spicy chicken with curry leaves.'},
  {id:10,name:'Chicken Lollipop',category:'starter',price:190,rating:'4.7',image:'assets/images/img/deserts.jpeg',description:'Juicy chicken lollipops with a smoky chilli glaze.'},
  {id:11,name:'Gobi Manchurian',category:'starter',price:130,rating:'4.6',image:'assets/images/img/family_dinning.jpeg',description:'Crisp cauliflower in an Indo-Chinese sauce.'},
  {id:12,name:'Gulab Jamun',category:'dessert',price:70,rating:'4.8',image:'assets/images/img/special_dish.jpeg',description:'Tender milk dumplings in cardamom sugar syrup.'},
  {id:13,name:'Ice Cream',category:'dessert',price:80,rating:'4.5',image:'assets/images/img/signature dish.png',description:'A creamy, chilled sweet finish to your meal.'},
  {id:14,name:'Brownie & Ice Cream',category:'dessert',price:140,rating:'4.9',image:'assets/images/img/deserts2.jpeg',description:'Warm chocolate brownie with a cool vanilla scoop.'}
];
let active='all'; let cart=JSON.parse(localStorage.getItem('ruchi-cart')||'[]');
const money=n=>`₹${Number(n).toLocaleString('en-IN')}`;
const save=()=>localStorage.setItem('ruchi-cart',JSON.stringify(cart));
const total=()=>cart.reduce((sum,item)=>sum+item.price*item.qty,0);
const card=d=>`<article class="dish"><img src="${d.image}" alt="${d.name}"><div class="dish-body"><div class="dish-top"><h3>${d.name}</h3><b class="dish-price">${money(d.price)}</b></div><p>${d.description}</p><div class="dish-bottom"><span class="rating">★ ${d.rating}</span><button class="add" data-add="${d.id}">+ ADD</button></div></div></article>`;
function renderMenu(){const target=document.querySelector('#menuGrid, [data-full-menu]');if(!target)return;const pool=target.matches('#menuGrid')?dishes.slice(0,10):dishes;target.innerHTML=pool.filter(d=>active==='all'||d.category===active).map(card).join('');}
function updateBadge(){const count=cart.reduce((sum,item)=>sum+item.qty,0);document.querySelectorAll('[data-cart-count]').forEach(node=>node.textContent=count);document.querySelector('#cartCount')?.replaceChildren(document.createTextNode(count));}
function renderCart(){const drawer=document.querySelector('#cartItems');const page=document.querySelector('[data-cart-page]');const rows=cart.length?cart.map(item=>`<div class="cart-line"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${money(item.price)} × ${item.qty}</p><div class="qty"><button data-qty="${item.id}" data-change="-1">−</button><b>${item.qty}</b><button data-qty="${item.id}" data-change="1">+</button><button data-remove="${item.id}">REMOVE</button></div></div><b>${money(item.price*item.qty)}</b></div>`).join(''):'<p class="empty-cart">Your cart is waiting for something delicious.</p>';if(drawer)drawer.innerHTML=rows;if(page)page.innerHTML=rows;document.querySelectorAll('[data-cart-total]').forEach(node=>node.textContent=money(total()));updateBadge();}
function add(id){const dish=dishes.find(d=>d.id===Number(id));const item=cart.find(i=>i.id===dish.id);if(item)item.qty+=1;else cart.push({...dish,qty:1});save();renderCart();showToast(`${dish.name} added to your order`);}
function change(id,amount){const item=cart.find(i=>i.id===Number(id));if(!item)return;item.qty+=Number(amount);if(item.qty<1)cart=cart.filter(i=>i.id!==item.id);save();renderCart();}
function showToast(message){let toast=document.querySelector('#toast');if(!toast){toast=document.createElement('div');toast.id='toast';document.body.append(toast)}toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item===button));renderMenu()}));
document.addEventListener('click',event=>{const addButton=event.target.closest('[data-add]');if(addButton)add(addButton.dataset.add);const quantity=event.target.closest('[data-qty]');if(quantity)change(quantity.dataset.qty,quantity.dataset.change);const remove=event.target.closest('[data-remove]');if(remove){cart=cart.filter(item=>item.id!==Number(remove.dataset.remove));save();renderCart();}});
document.querySelector('.add-special')?.addEventListener('click',()=>add(1));
const drawer=document.querySelector('#cart');const backdrop=document.querySelector('#cartBackdrop');const openCart=()=>{drawer?.classList.add('open');backdrop?.classList.add('show')};const closeCart=()=>{drawer?.classList.remove('open');backdrop?.classList.remove('show')};document.querySelectorAll('[data-open-cart], #openCart').forEach(button=>button.addEventListener('click',openCart));document.querySelector('#closeCart')?.addEventListener('click',closeCart);backdrop?.addEventListener('click',closeCart);
document.querySelectorAll('[data-checkout]').forEach(button=>button.addEventListener('click',()=>{if(!cart.length){showToast('Add a dish before checking out');return}location.href='payment.html'}));
document.querySelector('#bookingForm')?.addEventListener('submit',event=>{event.preventDefault();const name=new FormData(event.currentTarget).get('name');document.querySelector('#bookingMessage').textContent=`Thank you, ${name}. Your table request has been received — we’ll confirm shortly.`;event.currentTarget.reset();});
document.querySelector('#paymentForm')?.addEventListener('submit',event=>{event.preventDefault();if(!cart.length){location.href='menu.html';return}const id=`RUCHI-${Date.now().toString().slice(-7)}`;const order={id,total:total(),method:new FormData(event.currentTarget).get('payment'),date:new Date().toLocaleDateString('en-IN'),items:cart.map(item=>({name:item.name,qty:item.qty}))};const history=JSON.parse(localStorage.getItem('ruchi-order-history')||'[]');localStorage.setItem('ruchi-order-history',JSON.stringify([order,...history]));localStorage.setItem('ruchi-last-order',JSON.stringify(order));cart=[];save();location.href='thank-you.html';});
const order=JSON.parse(localStorage.getItem('ruchi-last-order')||'null');document.querySelectorAll('[data-order-id]').forEach(node=>node.textContent=order?.id||'—');document.querySelectorAll('[data-order-total]').forEach(node=>node.textContent=order?money(order.total):'—');document.querySelectorAll('[data-order-method]').forEach(node=>node.textContent=order?.method||'—');
document.querySelectorAll('[data-faq]').forEach(button=>button.addEventListener('click',()=>{const item=button.parentElement;document.querySelectorAll('.faq-item').forEach(faq=>faq.classList.toggle('open',faq===item&&!faq.classList.contains('open')))}));
document.querySelector('.nav-toggle')?.addEventListener('click',event=>{const nav=document.querySelector('.nav-links');nav.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
renderMenu();renderCart();
